---
- name: Workaround for OpenSLP security vulnerability in ESXi 6.7
  hosts: all
  tasks:
    - name: Stopping the SLP service
      shell: /etc/init.d/slpd stop
      register: slpd_stop

    - name: Print Stopping the SLP service
      debug:
        msg: "{{slpd_stop.stdout }}"

    - name: Disable the SLP service
      shell: esxcli network firewall ruleset set -r CIMSLP -e 0

    - name: change persist across reboots
      shell: chkconfig slpd off

    - name: Check if the change is applied across reboots
      shell: chkconfig --list | grep slpd
      register: check_change

    - name: Print the result of change
      debug:
        msg: "{{check_change.stdout }}"
